server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Accenemy/springcloud-config.git #github上面的git仓库名称
          ###搜索目录
          search-paths:
            - springcloud-config
      #读取分支
      label: main
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#rabbitMQ相关配置，暴露BUS刷新配置的端点。
management:
  endpoints:   #暴露bus属性配置的端点。
    web:
      exposure:
        include: 'bus-refresh'


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


